[build]
  command = "yarn build"
  functions = "vue-app/dist/lambda"
  publish = "vue-app/dist"

[context.staking-round.environment]
  VUE_APP_ETHEREUM_API_URL = "https://arb-rinkeby.g.alchemy.com/v2/wPwZJEp0lIu0XwccG_t0MAqF-phtI3og"
  VUE_APP_ETHEREUM_API_CHAINID = "421611"
  VUE_APP_CLRFUND_FACTORY_ADDRESS = "0x9cF8c20dAb0aAFC6584D5498C0A97F0F51D6F7E4"
  VUE_APP_SUBGRAPH_URL = "https://api.thegraph.com/subgraphs/name/pettinarip/clrfundrinkarby2"
  VUE_APP_USER_REGISTRY_TYPE = "brightid"
  VUE_APP_BRIGHTID_CONTEXT = "CLRFundTest"