#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# set these params so git push will work without .env
export VITE_ETHEREUM_API_CHAINID=100
export VITE_IPFS_PINNING_JWT=1

yarn test:format && yarn test:web && yarn test:lint-i18n
