name: Mantle testnet - Set voting duration

on:
  workflow_dispatch:
    inputs:
      voting_period:
        description: 'Voting period in minutes'
        required: true
        default: '120'
      reallocation_period:
        description: 'Reallocation period in minutes'
        required: true
        default: '1'
      factory:
        description: 'Clrfund factory address'
        required: true
        default: '0x006f39E6a6D15323334Be1db34C73088550BB20a'
      network:
        description: 'Network'
        required: true
        default: 'mantle-testnet'

env:
  NODE_VERSION: 16.x
  WALLET_PRIVATE_KEY: ${{ secrets.MANTLE_TESTNET_COORDINATOR_WALLET_PRIVATE_KEY }}

jobs:
  set-durations:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Build CLR
      run: |
        yarn && yarn build
    - name: Run the set duration script
      run: |
        cd contracts
        yarn hardhat set-durations --factory "${{ github.event.inputs.factory }}" --signup "${{ github.event.inputs.voting_period }}" --voting "${{ github.event.inputs.reallocation_period }}" --network "${{ github.event.inputs.network }}"
