name: Mantle testnet - Finalize round

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Clrfund branch name'
        required: true
        default: 'cohort/EthSingapore'
      maci_start_block:
        description: 'MACI contract creation block'
        required: true
        default: '1'
      subgraph_url:
        description: 'Clrfund subgraph url'
        required: true
        default: 'https://graph.testnet.mantle.xyz/subgraphs/name/clrfund-ethsingapore-test'
      network:
        description: 'Network'
        required: true
        default: 'mantle-testnet'

env:
  NODE_VERSION: 16.x
  COORDINATOR_ETH_PK: ${{ secrets.MANTLE_TESTNET_COORDINATOR_WALLET_PRIVATE_KEY }}
  COORDINATOR_PK: ${{ secrets.MANTLE_TESTNET_COORDINATOR_MACI_PRIVATE_KEY }}

jobs:
  finalize:
    runs-on: ubuntu-22.04
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch_name }}
    - name: Download batch 64 params
      run: |
        ls -la $GITHUB_WORKSPACE
        $GITHUB_WORKSPACE/.github/scripts/download-batch64-params.sh
    - name: Build
      run: |
        yarn && yarn build
    - name: Run finalize scripts
      run: |
        export SUBGRPAH_URL="${{ github.event.inputs.subgraph_url }}"
        echo $SUBGRAPH_URL
        export NODE_CONFIG=$(node -e "const snarkParamsPath=process.env.GITHUB_WORKSPACE + '/params'; console.log(JSON.stringify({ snarkParamsPath }));")
        export ROUND=$(curl -X POST -d '{"query":"{fundingRoundFactories {id currentRound {id maci}}}"}' $SUBGRPAH_URL)
        export FACTORY_ADDRESS=$(node -e 'console.log(JSON.parse(process.env.ROUND).data.fundingRoundFactories[0].id)')
        export ROUND_ADDRESS=$(node -e 'console.log(JSON.parse(process.env.ROUND).data.fundingRoundFactories[0].currentRound.id)')
        export MACI_ADDRESS=$(node -e 'console.log(JSON.parse(process.env.ROUND).data.fundingRoundFactories[0].currentRound.maci)')
        export MACI_START_BLOCK="${{ github.event.inputs.maci_start_block }}"
        echo "MACI_START_BLOCK:" $MACI_START_BLOCK
        # tally and finalize
        cd contracts
        yarn hardhat tally --round-address "${ROUND_ADDRESS}" --network "${{ github.event.inputs.network }}"
        curl --location --request POST 'https://api.pinata.cloud/pinning/pinFileToIPFS' \
          --header "Authorization: Bearer ${{ secrets.PINATA_JWT }}" \
          --form 'file=@"tally.json"'
        yarn hardhat run --network "${{ github.event.inputs.network }}" scripts/finalize.ts
