name: End to end tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

env:
  NODE_VERSION: 16.x
  CIRCUIT_TYPE: prod

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout MACI
      uses: actions/checkout@v3
      with:
        repository: privacy-scaling-explorations/maci
        ref: v0.10.1
        path: maci
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install g++ library dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential libgmp-dev libsodium-dev nlohmann-json3-dev nasm g++ curl
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install zkutil
      run: |
        cargo install zkutil --version 0.3.2
    - name: Checkout Clrfund
      uses: actions/checkout@v3
      with:
        path: monorepo
    - name: Download batch micro zk circuit params
      run: |
        $GITHUB_WORKSPACE/monorepo/.github/scripts/download-zkeys-micro.sh
    - name: Build Clrfund
      run: |
        cd monorepo
        yarn && yarn build
    - name: Start hardhat network
      run: |
        cd monorepo
        yarn start:node &
    - name: Run tests
      run: |
        export CIRCUIT_TYPE=micro
        export CIRCUIT_DIRECTORY==$GITHUB_WORKSPAC + '/params'
        echo $NODE_CONFIG
        cd monorepo
        yarn test:e2e

